from typing import Any, Protocol


class BrowserPage(Protocol):
    """Common interface for BridgePage and PlaywrightPage."""

    def navigate(self, url: str) -> None: ...

    def wait_for_load(self, timeout: float = 60.0) -> None: ...

    def wait_dom_stable(self, timeout: float = 10.0, interval: float = 0.5) -> None: ...

    def evaluate(self, expression: str, timeout: float = 30.0) -> Any: ...

    def has_element(self, selector: str) -> bool: ...

    def wait_for_element(self, selector: str, timeout: float = 30.0) -> str: ...

    def click_element(self, selector: str) -> None: ...

    def input_text(self, selector: str, text: str) -> None: ...

    def get_element_text(self, selector: str) -> str | None: ...

    def get_element_attribute(self, selector: str, attr: str) -> str | None: ...

    def get_elements_count(self, selector: str) -> int: ...

    def scroll_to_bottom(self) -> None: ...

    def scroll_element_into_view(self, selector: str) -> None: ...

    def set_file_input(self, selector: str, files: list[str]) -> None: ...

    def close(self) -> None: ...
